"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_ticks_id'), 'price_ticks', ['id'], unique=False)
    op.create_index(op.f('ix_price_ticks_ticker'), 'price_ticks', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_ticks_timestamp'), 'price_ticks', ['timestamp'], unique=False)
    op.create_index('idx_ticker_timestamp', 'price_ticks', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ticker_timestamp', table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_timestamp'), table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_ticker'), table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_id'), table_name='price_ticks')
    op.drop_table('price_ticks')
    # ### end Alembic commands ###
